fqncom/fqn.ItcastOA/fqn.ItcastOA.WebApp/Controllers/UserInfoController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Net.Cache;
using System.Web;
using System.Web.Mvc;
using fqn.ItcastOA.Bll;
using fqn.ItcastOA.Common;
using fqn.ItcastOA.Model;
using fqn.ItcastOA.Model.Enum;
using fqn.ItcastOA.Model.SearchModel;

namespace fqn.ItcastOA.WebApp.Controllers
{
    public class UserInfoController : BaseController
    {
        //
        // GET: /UserInfo/
        private IBll.IUserInfoBll UserInfoBll { get; set; }
        private IBll.IRoleInfoBll RoleInfoBll { get; set; }

        private IBll.IActionInfoBll ActionInfoBll { get; set; }
        private IBll.IR_UserInfo_ActionInfoBll R_UserInfo_ActionInfoBll { get; set; }


        public ActionResult Index()
        {
            return View();
        }

        #region 获取分页用户数据
        public ActionResult GetUserInfoList()
        {
            int pageIndex = Convert.ToInt32(Request["page"] ?? "1");
            int pageSize = Convert.ToInt32(Request["rows"] ?? "5");
            int rowCount = 0;
            UserInfoParams pars = new UserInfoParams()
            {
                UName = Request["UName"] ?? "",
                Remark = Request["Remark"] ?? "",
                RowSkip = (pageIndex - 1) * pageSize,
                RowTake = pageSize,
                RowCount = rowCount
            };


            var userInfoList = UserInfoBll.LoadSearchEntities(pars, false);
            //var userInfoList = bll.SelectPageEntities<int>(u => u.DelFlag == (short)DeleteFlag.Normal, u => u.ID, (pageIndex - 1) * pageSize, pageSize, out rowCount, false);
            var temp = (from u in userInfoList
                        select new
                        {
                            ID = u.ID,
                            UName = u.UName,
                            UPwd = u.UPwd,
                            Remark = u.Remark,
                            SubTime = u.SubTime
                        }).ToList();

            return Json(new { rows = temp, total = pars.RowCount }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region 逻辑删除用户
        public ActionResult DeleteUserInfo()
        {
            string deleteId = Request["DeleteId"] ?? "";
            if (deleteId == "")
            {
                return null;
            }
            string[] delIds = deleteId.Split(new char[] { ',' }, StringSplitOptions.RemoveEmptyEntries);
            List<int> listId = new List<int>();
            foreach (string delId in delIds)
            {
                listId.Add(Convert.ToInt32(delId));
            }
            return Content(UserInfoBll.DeleteEntitiesLogical(listId) ? "success" : "failed");
        }
        #endregion

        #region 新增用户
        public ActionResult AddUserInfo(UserInfo userInfo)
        {
            userInfo.SubTime = System.DateTime.Now;
            userInfo.ModifiedOn = System.DateTime.Now;
            userInfo.DelFlag = (short)DeleteFlag.Normal;
            return Content(UserInfoBll.AddEntity(userInfo) != null ? "success" : "failed");
        }
        #endregion

        #region 查询一个用户

        public ActionResult GetUserInfo()
        {
            int id = Convert.ToInt32(Request["Id"] ?? "-1");
            int rowCount = 0;
            UserInfo user = UserInfoBll.SelectEntities<UserInfo>(u => u.ID == id, out rowCount).FirstOrDefault();
            if (user != null)
            {
                return Json(new
                {
                    ID = user.ID,
                    UName = user.UName,
                    UPwd = user.UPwd,
                    Remark = user.Remark,
                    Sort = user.Sort,
                    SubTime = user.SubTime
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Content("failed");
            }
        }

        #endregion

        #region 编辑用户
        public ActionResult EditUserInfo(UserInfo userInfo)
        {
            userInfo.DelFlag = (short)DeleteFlag.Normal;
            userInfo.ModifiedOn = System.DateTime.Now;
            return Content(UserInfoBll.UpdateEntity(userInfo) ? "success" : "failed");
        }

        #endregion

        #region 测试错误日志记录

        public ActionResult TestLogRecord()
        {
            int a = 10;
            int b = 1;
            b--;
            return Content((a / b).ToString());
        }

        #endregion

        #region 查看用户角色

        public ActionResult GetRUserRoleInfo()
        {
            int id = Convert.ToInt32(Request["id"] ?? "-1");
            int rowCount = 0;
            UserInfo user = UserInfoBll.SelectEntities<UserInfo>(u => u.ID == id, out rowCount).FirstOrDefault();
            if (user != null)
            {
                ViewBag.UserInfo = user;
                List<RoleInfo> roleInfoList = RoleInfoBll.SelectEntities<RoleInfo>(r => r.DelFlag == (short)DeleteFlag.Normal, out rowCount).ToList();
                List<int> userRoleIdList = (from ur in user.RoleInfo
                                            select ur.ID).ToList();

                ViewBag.RoleInfoList = roleInfoList;
                ViewBag.UserRoleIdList = userRoleIdList;
                return View();
            }

            return Content("页面找不到了");

        }

        #endregion

        #region 编辑用户角色

        public ActionResult EditRUserRoleInfo()
        {
            int userId = Convert.ToInt32(Request["UserId"] ?? "-1");
            string[] allKeys = Request.Form.AllKeys;
            List<int> roleIdList = new List<int>();
            foreach (string key in allKeys)
            {
                if (key.StartsWith("ch_"))
                {
                    string k = key.Replace("ch_", "");
                    roleIdList.Add(Convert.ToInt32(k));
                }
            }
            return Content(UserInfoBll.UpdateUserRoleInfo(userId, roleIdList) ? "success" : "failed");
        }

        #endregion

        #region 显示用户的特殊权限

        public ActionResult ShowUserActionInfo()
        {
            int userId = Convert.ToInt32(Request["userId"] ?? "-1");
            int rowCount = 0;
            var userInfo = UserInfoBll.SelectEntities<UserInfo>(u => u.ID == userId && u.DelFlag == (short)DeleteFlag.Normal, out rowCount).FirstOrDefault();
            if (userInfo != null)
            {
                ViewBag.UserInfo = userInfo;
                ViewBag.UserActionInfoList = (from u in userInfo.R_UserInfo_ActionInfo
                                              select u).ToList();
                ViewBag.ActionInfoList = ActionInfoBll.SelectEntities<ActionInfo>(a => a.DelFlag == (short)DeleteFlag.Normal,
                    out rowCount).ToList();
                return View();
            }
            return Content("something wrong");
        }

        #endregion

        #region 为用户指定特殊权限

        public ActionResult SetUserInfoActionInfo()
        {

            int userId = Convert.ToInt32(Request["userId"] ?? "-1");
            int actionId = Convert.ToInt32(Request["actionId"] ?? "-1");
            bool isPass = Request["IsPass"] == "true";
            int rowCount = 0;
            UserInfo userInfo = UserInfoBll.SelectEntities<UserInfo>(u => u.ID == userId && u.DelFlag == (short)DeleteFlag.Normal,
                 out rowCount).FirstOrDefault();
            if (userInfo != null)
            {
                R_UserInfo_ActionInfo userAction = (from ru in userInfo.R_UserInfo_ActionInfo
                                                    where ru.ActionInfoID == actionId
                                                    select ru).FirstOrDefault();

                if (userAction != null)
                {
                    userAction.IsPass = isPass;
                    R_UserInfo_ActionInfoBll.UpdateEntity(userAction);
                }
                else
                {
                    userAction = new R_UserInfo_ActionInfo();
                    userAction.ActionInfoID = actionId;
                    userAction.IsPass = isPass;
                    userAction.UserInfoID = userInfo.ID;
                    R_UserInfo_ActionInfoBll.AddEntity(userAction);
                }
                return Content("success");
            }

            return Content("failed");
        }

        #endregion

        #region 清除用户权限

        public ActionResult ClearUserActionInfo()
        {
            int userId = Convert.ToInt32(Request["userId"] ?? "-1");
            int actionId = Convert.ToInt32(Request["actionId"] ?? "-1");
            int rowCount = 0;
            var r_userInfo_ActionInfo =
                R_UserInfo_ActionInfoBll.SelectEntities<R_UserInfo_ActionInfo>(
                    ru => ru.UserInfoID == userId && ru.ActionInfoID == actionId, out rowCount).FirstOrDefault();
            return Content(R_UserInfo_ActionInfoBll.DeleteEntity(r_userInfo_ActionInfo) ? "success" : "failed");
        }

        #endregion

       

    }
}

fqncom/fqn.ItcastOA/fqn.ItcastOA.WebApp/Views/UserInfo/GetRUserRoleInfo.cshtml
@using fqn.ItcastOA.Model
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>EditR_UserRoleInfo</title>
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    <script>
        $(function() {

        });

        function SubmitForm() {
            $('#formEditR_UserRoleInfo').submit();
        }

        function EditUserRoleInfoSuccess() {
            window.parent.EditUserRoleInfoSuccess();
        }
    </script>
</head>

<body>
    <div>
        为用户
        @{
            UserInfo userInfo = ViewBag.UserInfo;
            <span style="font-size:14px;color:red"> @userInfo.UName</span>
        }分配角色

        @using (Ajax.BeginForm("EditRUserRoleInfo", "UserInfo", new { }, new AjaxOptions { HttpMethod = "post", OnSuccess = "EditUserRoleInfoSuccess" }, new { id = "formEditR_UserRoleInfo" }))
        {
            List<RoleInfo> roleInfoList = ViewBag.RoleInfoList;
            List<int> roleIdList = ViewBag.UserRoleIdList;

            <input id="hidUserId" type="hidden" name="UserID" value="@userInfo.ID" />
            <table>
                <th>
                    角色名：
                </th>
                <th>
                    选中
                </th>
                @foreach (var roleInfo in roleInfoList)
                {
                    string checkStr = roleIdList.Contains(roleInfo.ID) ? "checked = 'checked'" : "";
                    string chName = "ch_" + roleInfo.ID;
                    <tr>
                        <td>@roleInfo.RoleName</td>

                        <td><input type="checkbox" name="@chName" value="" @checkStr /></td>
                    </tr>
                }
            </table>
        }
    </div>
</body>
</html>

fqncom/fqn.ItcastOA/fqn.ItcastOA.WebApp/Views/UserInfo/ShowUserActionInfo.cshtml
@{
    Layout = null;
}
@using fqn.ItcastOA.Model
@using fqn.ItcastOA.Model
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>为用户分配权限</title>
    <link href="~/Content/tableStyle.css" rel="stylesheet" />
    <link href="~/Content/themes/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/themes/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.8.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
</head>
<body>
    <div>
        为用户 @{
            UserInfo userInfo = ViewBag.UserInfo;
            <span style="font-size:14px;color:red"> @userInfo.UName</span>
        }分配权限

        @using (Ajax.BeginForm("SetUserInfoActionInfo", "UserInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterSet" }, new { id = "setUserAction" }))
        {
            List<ActionInfo> actionInfoList = ViewBag.ActionInfoList;
            List<R_UserInfo_ActionInfo> userInfoActionInfoList = ViewBag.UserActionInfoList;
            <table>
                <tr>
                    <th>权限编号</th>
                    <th>权限名称</th>
                    <th>地址</th>
                    <th>请求方式</th>
                    <th>操作</th>
                </tr>
                @foreach (var actionInfo in actionInfoList)
                {
                    var rb_name = "cba_" + actionInfo.ID;
                    var norb_name = "nocba_" + actionInfo.ID;

                    string allowStr = "";
                    string disallowStr = "";
                    var isExt = (from a in userInfoActionInfoList
                                 where a.ActionInfoID == actionInfo.ID
                                 select a).FirstOrDefault();
                    if (isExt != null)//表示用户有权限
                    {
                        allowStr = isExt.IsPass == true ? "checked='checked'" : "";
                        disallowStr = isExt.IsPass == false ? "checked='checked'" : "";
                    }
                    <tr>
                        <td>@actionInfo.ID</td>
                        <td>@actionInfo.ActionInfoName</td>
                        <td>@actionInfo.Url</td>
                        <td>@actionInfo.HttpMethod</td>
                        <td>
                            <label for="@rb_name">
                                允许
                            </label>
                            <input type="radio" name="@rb_name" id="@rb_name" value="true" class="setactions" ids="@actionInfo.ID" @allowStr />
                            <label for="@norb_name">拒绝</label>
                            <input type="radio" name="@rb_name" id="@norb_name" value="false" class="setactions" ids="@actionInfo.ID" @disallowStr />
                            <input type="button" value="清除" class="btnClear" ids="@actionInfo.ID" />
                        </td>
                    </tr>
                }
            </table>

        }

    </div>
</body>
</html>
<script type="text/javascript">
    $(function () {
        $(".setactions").click(function () {
            var $control = $(this);
            $.post("/UserInfo/SetUserInfoActionInfo", {"userId":@userInfo.ID ,"actionId":$control.attr("ids"),"IsPass":$control.val()}, function (data) {
                if(data=="success"){
                    $.messager.show({
                        title: '设置权限',
                        msg: '用户设置权限成功!!',
                        showType: 'show'
                    });
                }else{
                    $.messager.show({
                        title: '设置权限',
                        msg: '用户设置权限失败!!',
                        showType: 'show'
                    });
                }
            });
        });

        $(".btnClear").click(function(){
            var $control = $(this);
            $.post("/UserInfo/ClearUserActionInfo",{"userId":@userInfo.ID ,"actionId":$control.attr("ids")},function(data){
                if(data=="success"){
                    $control.parent().find(".setactions").removeAttr("checked");
                    $.messager.show({
                        title: '清除权限',
                        msg: '清除权限成功!!',
                        showType: 'show'
                    });
                }else{
                    $.messager.show({
                        title: '清除权限',
                        msg: '清除权限失败!!',
                        showType: 'show'
                    });
                }
            });
        });
    });



</script>